// config.bin - 13:29:28 04/03/13, generated in 0.12 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class RscStandardDisplay {
	access = ReadAndWrite;
	movingEnable = 1;
	enableSimulation = 1;
	enableDisplay = 1;
};
